[package]
name = "polaris-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossbeam-channel = "0.5.15"
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["rt", "macros", "rt-multi-thread"] }
